language: node_js
env:
- CODECOV_TOKEN="b2c5ff6b-5b47-40b0-aabd-59d2e4c10308"
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"

after_success:
  - npm run coverage
  - codecov
  - cat ./coverage/lcov.info | coveralls
  - bash <(curl -s https://codecov.io/bash)
